### ISSUE TITLE
More verbose semver.compare

### ISSUE THREAD

**Issue by averrin** [k-bx/python-semver#17]
Please make
semver.compare('0.2.0', '0.1.0') != semver.compare('0.1.1', '0.1.0')

**Comment by k-bx** [comment]
@averrin why would you need something like this? What return-value would you suggest?

**Comment by averrin** [comment]
My case:
i have two versions:
1) current app
2) in saved file
if changed only patch - ignore, else perform some migration actions

About return:
maybe something like
(('major', 0), ('minor', 1), ('patch', 0))

**Comment by k-bx** [comment]
@averrin this case is quite rare, I would suggest doing manually:

```python
import semver
# ...
v1, v2 = semver.parse(ver1), semver.parse(ver2)
if v1['major'] > v2['major'] or v1['minor'] > v1['minor']:
    do_migrate()
```

**Comment by averrin** [comment]
I did it before create issue :)
but i use split('.')
just i think, 0 or 1 as return values is not a pythonic way, also just positive answer isnt very useful

**Comment by k-bx** [comment]
@averrin I don't see anything better than returning -1, 0 and 1. Python doesn't have union-types so that I could express LT, GT and EQ.

Also, standard library has function cmp for comparing things, which behaves similarly https://docs.python.org/2/library/functions.html#cmp , also it has "sorted" function, which also gets parameter with similar signature, so I do think it's quite pythonic.

I'd say using split('.') is worse, since it doesn't check full version format, and also if you'd want to work with "patch" (which you don't in this case) part you wouldn't be able to.

I don't mind adding some nice abstraction to get a sense "how exactly do versions differ", but I don't think something like `(('major', 0), ('minor', 1), ('patch', 0))` look nice, to be honest. We can think of something better.

**Comment by eugene-eeo** [comment]
Return a tuple- (0,1,0) > (0,0,1). Retains the original semantics and does what you wish.

**Comment by k-bx** [comment]
@eugene-eeo the function of comparing two versions is already available as `semver.compare`. The task for this issue is to not only compare versions, but also understand the "level of their difference".

One possible solution would be a function like `compare_detailed`, which would return a tuple, first item would be result (`-1`, `0` or `1`), and second would be some enum-value for determining major, minor, patch etc.

**Comment by djgilcrease** [comment]
sounds more like what he wants is semver.match(">0.1.0 <0.2.0")

**Comment by k-bx** [comment]
@djgilcrease that could be done as `.match('>0.1.0') and .match('<0.2.0')`

**Comment by bignose-debian** [comment]
With a “version info” tuple, as requested in https://github.com/k-bx/python-semver/issues/36 this could be done with:

```
import semver
version_info_foo = semver.parse_version_info("0.1.0")
version_info_bar = semver.parse_version_info("0.1.1")
assert version_info_foo[:2] == version_info_bar[:2]
```

**Comment by k-bx** [comment]
Closing for now
