### ISSUE TITLE
Fix travis under 2.6

### ISSUE THREAD

**Issue by k-bx** [k-bx/python-semver#57]
For some reason, that interpreter stopped being installed in travis

**Comment by ppkt** [comment]
@k-bx I just checked Travis documentation and it seems that there might be a problem with tox and Travis. It's because we are asking Travis to configure environment only for Python 3.5 (see [here](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against)).

Maybe external library, like [tox-travis](https://github.com/ryanhiebert/tox-travis) could help?

**Comment by k-bx** [comment]
@ppkt yeah, maybe. Not sure I'll have time for this in the nearest time, so PRs are welcome!
