### ISSUE TITLE
Wrong version of semver

### ISSUE THREAD

**Issue by nowox** [k-bx/python-semver#67]
I was surprised the `semver` I got was different from the one I installed...

```
$ pip install semver
Collecting semver
  Downloading semver-2.7.9.tar.gz
Building wheels for collected packages: semver
  Running setup.py bdist_wheel for semver ... done
  Stored in directory: /cygdrive/c/Users/Ycr/Home/.cache/pip/wheels/50/53/f6/4b3f5e28484ca571be4c53373033a07c699d175cdd3337129d
Successfully built semver
Installing collected packages: semver
Successfully installed semver-2.7.9
```

And what I get is 

```
>>> import semver
>>> semver.__path__
['/usr/lib/python2.7/site-packages/semver']
>>> semver.SEMVER_SPEC_VERSION
'2.0.0'
```

So it seems I got two semver packages that are in conflict:

```
$ ls /usr/lib/python2.7/site-packages | grep semver
node_semver-0.1.1.dist-info/
semver/
semver.py
semver.pyc
semver-2.7.9.dist-info/
```

So it seems Python uses the `semver/` instead of `semver.py`.  Is this something expected?

I am on Cygwin

```
$ uname -a
CYGWIN_NT-6.1 MYPC 2.9.0(0.318/5/3) 2017-09-08 10:19 x86_64 Cygwin
```

**Comment by k-bx** [comment]
@nowox I don't think the problem is related to the semver package. Python uses an environment variable called `PYTHONPATH` to figure its list of directories in which it would search for installed module. Your setup has some mis-configuration between pip and PYTHONPATH. Please ask about this on StackOverflow, Python forums/mailing lists or other places for further assistance. Thank you!

**Comment by Reonaydo** [comment]
This problem becouse two pip packages have same module name: semver.

`semver.SEMVER_SPEC_VERSION` is from node-semver package( https://pypi.org/project/node-semver/ )
