### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by chaddotson** [k-bx/python-semver#91]
Is this package compatible with npm's semantic versioning?

**Comment by ppkt** [comment]
@chaddotson this package relies on official semantic versioning document: https://semver.org/

If node follows the same rules, this package is compatible (and by looking on documents: https://docs.npmjs.com/getting-started/semantic-versioning it is). However this package does not support node-specific matching syntax, see #25.

**Comment by vp93** [comment]
@chaddotson  " With v0.8, v0.10, v0.11, v0.12 (commonly casually pronounced 8, 10, 11 and 12), we have grown accustomed to Node.js’s pre-1.0 versioning. So much so that they are frequently referred to dropping the 'zero dot'.  "   doc here : https://medium.com/@nodesource/node-js-is-semver-8b3938ae8d24

Yes, the node package fully embraces npm's semantic versioning. Current actively LTS is node v8.x.x , conducting semver patch releases monthly and other minor semver releases quarterly.  

Semver also has a provision for pre-release tags and these will be released from the Master Node.js branch.
